<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Authors>Piotr Falkowski</Authors>
    <Description>Persistence layer for stocks using Entity Framework Core.</Description>
    <Copyright>Piotr Falkowski © 2026</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/PFalkowski/StocksData</PackageProjectUrl>
    <RepositoryUrl>https://github.com/PFalkowski/StocksData</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Stock, Data, EntityFrameworkCore, UnitOfWork, Repository</PackageTags>
    <Version>3.1.0</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="StandardInterfaces" Version="3.1.0" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stocks.Data.Common\Stocks.Data.Common.csproj" />
    <ProjectReference Include="..\Stocks.Data.Model\Stocks.Data.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
